image: bergwerkio/phoenix-1.3:1.0
pipelines:
  default:
    - step:
        caches:
          - deps
          - build
        script:
          - mix deps.get
          - MIX_ENV=test mix deps.get
          - MIX_ENV=test mix ecto.reset
          - mix test
        services:
        - database

definitions:
  caches:
    deps: deps
    build: _build
  services:
    database:
      image: postgres:9.6-alpine
      environment:
        POSTGRES_PASSWORD: pipelines-test